name: OKEmby 自动归集

on:
  schedule:
    - cron: "0 9 * * *" # 每天9点执行
  workflow_dispatch:

jobs:
  okemby:
    runs-on: ubuntu-latest
    env:
      OKEMBY_ACCOUNTS: ${{ secrets.OKEMBY_ACCOUNTS }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests
          playwright install

      - name: 运行 OKEmby 脚本
        run: python okemby_playwright.py
